# Generated by Django 4.2.2 on 2023-06-11 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commissions_USF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.CharField(choices=[('APERTURA DE CUENTAS', 'APERTURA DE CUENTAS'), ('GASTOS DE MANTENIMIENTO', 'GASTOS DE MANTENIMIENTO'), ('GASTOS DE ADMINISTRACION DE CHEQUES', 'GASTOS DE ADMINISTRACION DE CHEQUES'), ('GIROS Y TRANSFERENCIAS', 'GIROS Y TRANSFERENCIAS'), ('EMBARGOS Y OFICIOS JUDICIALES', 'EMBARGOS Y OFICIOS JUDICIALES'), ('OTROS GASTOS / COMISIONES ADMINISTRATIVOS Y DE SERVICIOS', 'OTROS GASTOS / COMISIONES ADMINISTRATIVOS Y DE SERVICIOS')], default='APERTURA DE CUENTAS', max_length=100)),
                ('id_subcategory', models.CharField(choices=[('General', 'General'), ('Gastos de Apertura Cuenta Corriente', 'Gastos de Apertura Cuenta Corriente'), ('Requisitos', 'Requisitos'), ('Cajas de Seguridad', 'Cajas de Seguridad'), ('Mantenim. de Cuenta Corriente "Operativa"/ Cuenta especial Ley 27260', 'Mantenim. de Cuenta Corriente "Operativa"/ Cuenta especial Ley 27260'), ('Resumen de cuenta impreso - a requerimiento del Cliente', 'Resumen de cuenta impreso - a requerimiento del Cliente'), ('Otros gastos', 'Otros gastos'), ('Cheques Rechazados de terceros', 'Cheques Rechazados de terceros'), ('Cheques Rechazados propios (por cheque)', 'Cheques Rechazados propios (por cheque)'), ('Clearing de Cheques', 'Clearing de Cheques'), ('Giros y Transferencias Nacionales', 'Giros y Transferencias Nacionales'), ('Giros y Transferencias Internacionales', 'Giros y Transferencias Internacionales'), ('Fotocopias', 'Fotocopias')], default='General', max_length=100)),
                ('date_of_entry', models.DateField()),
                ('name_commission', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('type_commission', models.CharField(choices=[('SIN CARGO', 'SIN CARGO'), ('SOLO COSTO', 'SOLO COSTO'), ('CON CARGO', 'CON CARGO')], default='CON BENEFICIO', max_length=100)),
                ('type_cost', models.CharField(choices=[('N/A', 'N/A'), ('%', 'INGRESO VARIABLE'), ('$', 'INGRESO FIJO')], default='$', max_length=50)),
                ('currency', models.CharField(choices=[('N/A', 'N/A'), ('PESOS', 'PESOS'), ('DÓLARES', 'DÓLARES')], default='PESOS', max_length=50)),
                ('frequency', models.CharField(choices=[('N/A', 'N/A'), ('EN SU OPORTUNIDAD', 'EN SU OPORTUNIDAD'), ('ANUAL', 'ANUAL'), ('SEMESTRAL', 'SEMESTRAL'), ('TRIMESTRAL', 'TRIMESTRAL'), ('MENSUAL', 'MENSUAL'), ('DIARIA', 'DIARIA')], default='EN SU OPORTUNIDAD', max_length=50)),
                ('application_base', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Input_Commissions_USF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_entry', models.DateField()),
                ('name_employee', models.CharField(max_length=50)),
                ('minimum_amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('fixed_amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('maximum_amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('additional_amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('idfk_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissions_usf')),
            ],
        ),
        migrations.CreateModel(
            name='Discount_CommissionsBank_USF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_employee', models.CharField(max_length=50)),
                ('name_client', models.CharField(max_length=50)),
                ('percent_discount', models.IntegerField()),
                ('application_base', models.CharField(blank=True, max_length=100, null=True)),
                ('idfk_commission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commission.commissions_usf')),
            ],
        ),
    ]
