# Generated by Django 4.2.1 on 2023-06-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commissions_usf',
            options={'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='discount_commissionsbank_usf',
            options={'verbose_name': 'Descuento de comisión', 'verbose_name_plural': 'Descuentos de comisiones'},
        ),
        migrations.AlterModelOptions(
            name='input_commissions_usf',
            options={'verbose_name': 'Valor de comisión', 'verbose_name_plural': 'Valores de Comisiones'},
        ),
        migrations.AlterField(
            model_name='commissions_usf',
            name='name_commission',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
