# Generated by Django 4.2.2 on 2023-06-15 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0002_alter_commissions_usf_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissions_usf',
            name='type_cost',
            field=models.CharField(choices=[('N/A', 'N/A'), ('VARIABLE', 'VARIABLE'), ('FIJO', 'FIJO')], default='$', max_length=50),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
    ]
